#! /bin/sh

## This is from p4est and likely not going to survive
# Call this without arguments if bfam is the toplevel package.
# Call this with one argument if bfam is itself a subdirectory:
# ./bootstrap <sc config directory>

# Currently we do not assume the sc source, we just copy some files

bdie () {
	echo "bootstrap aborting: $1"
	exit 1
}

# # override by option argument
# SC_CONFIG="sc/config"
# if test -n "$1" ; then
#   SC_CONFIG="$1"
# fi
# if test ! -d "$SC_CONFIG" ; then
#   echo "Error: Cannot find directory $SC_CONFIG"
#   echo "   If you just called ./bootstrap from a fresh clone of p4est"
#   echo "   you may need to checkout the submodule sc:"
#   echo "   \$ git submodule init && git submodule update"
#   exit 1
# fi
# # convert into an absolute path
# SC_CONFIG=`cd "$SC_CONFIG" && pwd`
# 
# if test -x "sc/bootstrap" ; then
#   echo "Running bootstrap in subdirectory sc"
#   (cd sc && ./bootstrap)
# fi

echo "--- This is the bootstrap script for bfam ---"
echo "Current directory is $PWD"

LIBTOOLIZE=`which glibtoolize`
if test ! -x "$LIBTOOLIZE" ; then LIBTOOLIZE=`which libtoolize` ; fi
if test ! -x "$LIBTOOLIZE" ; then echo "bootstrap requires libtoolize" ; \
   exit 1 ; fi

aclocal -Wall -I autotools || bdie "Error from aclocal"
autoconf -Wall --force || bdie "Error from autoconf"
autoheader -Wall --force || bdie "Error from autoheader"
"$LIBTOOLIZE" --install --copy || bdie "Error from libtoolize"
automake -Wall --add-missing --copy --foreign || bdie "Error from automake"
